### ISSUE TITLE
Pointnet++ implementation for ShapeNet Part Segmentation

### ISSUE THREAD

**Issue by 99DHL** [guochengqian/PointNeXt#120]
Thank you for your great work!
I cannot find any config that can run pointnet++ for ShapeNet part segmentation.
Could you please provide the config file?
I tried to write config by myself but it is not working. Loss becomes NaN after few steps. 

```
model:
  NAME: BasePartSeg
  encoder_args:
    NAME: PointNet2Encoder
    in_channels: 7
    width: null
    strides: [4, 4, 1]
    layers: 3
    use_res: False
    mlps: [[[64, 64, 128]],
        [[128, 128, 256]],
        [[256, 512, 1024]]]
    radius: [0.2, 0.4, null]
    num_samples: [32, 64, null]
    sampler: fps
    aggr_args:
      NAME: 'convpool'
      feature_type: 'dp_fj'
      anisotropic: False
      reduction: 'max'
    group_args:
      NAME: 'ballquery'
      use_xyz: True
    conv_args:
      order: conv-norm-act
    act_args:
      act: 'relu'
    norm_args:
      norm: 'bn'
  decoder_args:
    NAME: PointNet2PartDecoder
    fp_mlps: [[128, 128, 128], [256, 128], [256, 256]]
    norm_args:
      norm: 'bn'
  cls_args:
    NAME: SegHead
    globals: max,avg  # apped global feature to each point feature
    num_classes: 50
    in_channels: null
    norm_args:
      norm: 'bn'
```
